Const
  laName                    = 0;
  laTxtFiles                = 1;
  laMenus                   = 2;
  laNews                    = 3;
  laRawXLAT                 = 4;
  laAskXLAT                 = 5;
  laEnterForCont            = 6;
  laXLATs                   = 7;
  laChooseXLAT              = 8;
  laLoginNAllow             = 9;
  laOnAnotherLine           = 10;
  laYourNameNotFound        = 11;
  laNameEntered             = 12;
  laWantToReg               = 13;
  laPassword                = 14;
  laPassTooShort            = 15;
  laOutOfTryes              = 16;
  laPasswordNotValid        = 17;
  laChoosePassword          = 18;
  laRepeatPassword          = 19;
  laPasswordsNotSame        = 20;
  laForbiddenPassword       = 21;
  laRegResume               = 22;
  laChooseEmulation         = 23;
  laAlias                   = 24;
  laAliasExist              = 25;
  laLocation                = 26;
  laOrganization            = 27;
  laFidoAddress             = 28;
  laAddress1                = 29;
  laAddress2                = 30;
  laAddress3                = 31;
  laHomePhone               = 32;
  laDataPhone               = 33;
  laBirthDate               = 34;
  laDispLines               = 35;
  laPausing                 = 36;
  laUseFrames               = 37;
  laUseHotKeys              = 38;
  laUseFSeditor             = 39;
  laFsAnsiReq               = 40;
  laIsRegCorrect            = 41;
  laToEventLeft             = 42;
  laEventExit               = 43;
  laAborted                 = 44;
  laInactive                = 45;
  laHangUpInactive          = 46;
  laLogOff                  = 47;
  laLogoffMessage           = 48;
  laSelectFile              = 49;
  laWantToRead              = 50;
  laFilesMore               = 51;
  laTagFilesNum             = 52;
  laMoreNums                = 53;
  laMore                    = 54;
  laYesNo                   = 55;
  laNoYes                   = 56;
  laYesNoKeys               = 57;
  laYesNoQuit               = 58;
  laNoYesQuit               = 59;
  laYNQKeys                 = 60;
  laYes                     = 61;
  laNo                      = 62;
  laQuit                    = 63;
  laOutPageTime             = 64;
  laTopicForChat            = 65;
  laPageLimit               = 66;
  laPagingForChat           = 67;
  laNoSysOpForChat          = 68;
  laSysOpBusy               = 69;
  laSysOpAnswered           = 70;
  laBeginChat               = 71;
  laEndChat                 = 72;
  laPrivate                 = 73;
  laPauseAfterEach          = 74;
  laMsgHead                 = 75;
  laMsgNum                  = 76;
  laMsgFrom                 = 77;
  laMsgTo                   = 78;
  laMsgSubj                 = 79;
  laMsgFooter               = 80;
  laPrivMsg                 = 81;
  laQuoteMsg                = 82;
  laQueryPrivate            = 83;
  laUpLoadMsg               = 84;
  laEditStatusLine          = 85;
  laSure                    = 86;
  laMsgString               = 87;
  laMsgKeys                 = 88;
  laNoMoreMessages          = 89;
  laNoPrevMsg               = 90;
  laMsgSaved                = 91;
  laErrorSaveMsg            = 92;
  laDeleteMsg               = 93;
  laNextMsg                 = 94;
  laReplyNextMsg            = 95;
  laWantToAnswer            = 96;
  laUnknownMsgFormat        = 97;
  laMsgOpenError            = 98;
  laErrorMBClose            = 99;
  laNoMsgsInArea            = 100;
  laMsgWriteText1           = 101;
  laMsgWriteText2           = 102;
  laMsgWriteText3           = 103;
  laWriteMsgFooter          = 104;
  laPostMenu                = 105;
  laPostKeys                = 106;
  laEnterMsgLine            = 107;
  laDelLines                = 108;
  laEnterMsgNums            = 109;
  laListHeader              = 110;
  laSelectProtocol          = 111;
  laProtocolStr             = 112;
  laChooseMsgGroup          = 113;
  laChooseMsgArea           = 114;
  laChooseFileGroup         = 115;
  laChooseFileArea          = 116;
  laYourChoice              = 117;
  laFindNewFiles            = 118;
  laNewSinceDate            = 119;
  laScanFileAreas           = 120;
  laNoFilesFound            = 121;
  laFreeDL                  = 122;
  laPrevTagArea             = 123;
  laFromUsersArea           = 124;
  laFileFromUser            = 125;
  laNoFilesSelected         = 126;
  laFAreaLine               = 127;
  laFAreaKeys               = 128;
  laAddFile                 = 129;
  laAddFileNotFound         = 130;
  laDelFileNo               = 131;
  laClearList               = 132;
  laEmptyFArea              = 133;
  laSecurityLow             = 134;
  laTooSlow                 = 135;
  laAccessDenied            = 136;
  laTimeLimit               = 137;
  laDLTimeLimit             = 138;
  laDLLimitExceed           = 139;
  laScanMsgAreas            = 140;
  laFoundPrivMsg            = 141;
  laNoPrivFound             = 142;
  laMsgMaskGet              = 143;
  laMsgMaskSearch           = 144;
  laMsgMaskNotFound         = 145;
  laDownLoadDescs           = 146;
  laDownLoadHead1           = 147;
  laDownLoadHead2           = 148;
  laDownLoadHead3           = 149;
  laDownLoadHead4           = 150;
  laSendFile                = 151;
  laRecvFile                = 152;
  laUpLoadSpace             = 153;
  laUpLoadPlus              = 154;
  laULDescription           = 155;
  laLocalDownLoad           = 156;
  laLocalDLDir              = 157;
  laLdDirNotFound           = 158;
  laLocalUpLoad             = 159;
  laLocalULFileName         = 160;
  laLuFileNotFound          = 161;
  laCopyFile                = 162;
  laCopyTo                  = 163;
  laCopyOk                  = 164;
  laCopyError               = 165;
  laCopyDone                = 166;
  laULforuser               = 167;
  laUserName                = 168;
  laUsersHead               = 169;
  laUser                    = 170;
  laUserNotFound            = 171;
  laEnterUsrNums            = 172;
  laInfoLoc                 = 173;
  laInfoName                = 174;
  laInfoOrg                 = 175;
  laInfoAddress1            = 176;
  laInfoAddress2            = 177;
  laInfoAddress3            = 178;
  laInfoHPhone              = 179;
  laInfoBPhone              = 180;
  laInfoFirstCall           = 181;
  laInfoLastCall            = 182;
  laInfoBirthDate           = 183;
  laInfoSecurity            = 184;
  laInfoCallNum             = 185;
  laQueryArcName            = 186;
  laNotArchive              = 187;
  laArcName                 = 188;
  laArcHead                 = 189;
  laAskFileName             = 190;
  laFileName                = 191;
  laNotFound                = 192;
  laAlreadyExists           = 193;
  laMissing                 = 194;
  laNextBulletin            = 195;
  laSearchPrivateMsg        = 196;
  laSearchMask              = 197;
  laSearchDesc              = 198;
  laTodaysHead              = 199;
  laQWKscan                 = 200;
  laQWKajust                = 201;
  laQWKnotFound             = 202;
  laQWKlist                 = 203;
  laQWKEnterNum             = 204;
  laQWKcontrols             = 205;
  laNoQWKareas              = 206;
  laQWKadded                = 207;
  laQWKdeleted              = 208;
  laREPok                   = 209;
  laTRCline                 = 210;
  laTRCjoined               = 211;
  laTRCleft                 = 212;
  laTRCentered              = 213;
  laTRCleftBBS              = 214;
  laMsgsEnabled             = 215;
  laMsgsDisabled            = 216;
  lamlMessageFrom           = 217;
  laSendMessage             = 218;
  laMsgFromSysOp            = 219;
  lamlLine                  = 220;
  laLineNumber              = 221;
  laLineStatus              = 222;
  laLineDisabled            = 223;
  laTelnTrying              = 224;
  laTelnConnected           = 225;
  laTelnConnection          = 226;
  laTelnClosed              = 227;
  laCannotConnect           = 228;
  laUnableToResolve         = 229;

  laLastLanguageNum         = 229;

Type
 tFListFormat = (fFilesBBS, fCDList);

 PMsgHead = ^tMsgHead;
 tMsgHead = Record
   MsgNum, NumOfMsgs : LongInt;
   FromAddr, ToAddr  : TAddress;
   IsPriv, IsRcvd    : Boolean;
   MsgDateMBDT       : TMessageBaseDateTime;
   MsgDate           : DateTime;
   MsgFrom, MsgTo,
   MsgSubj, MSGID,
   eMail             : String [80];
 End;

 tMsgGroup = Record
   Name                            : String [72];
   Tag                             : String [15];
   ShowSec                         : System. Word;
   ShowFlags                       : String [26];
 End;

 tMsgArea = Record
   Name, Origin, GateWay                               : String [72];
   Address                                             : TAddress;
   BasePath                                            : String [80];
   BaseType                                            : TMessageBaseFormat;
   ReadSec, WriteSec, SysOpSec, ShowSec                : System. Word;
   ReadFlags, WriteFlags, SysOpFlags, ShowFlags        : String [26];
   ScanPrivMail                                        : Boolean;
   Group                                               : String [15];
   AreaType                                            : TBaseType;
   Private                                             : AskType;
  End;

 tFileGroup = Record
   Name                            : String [72];
   Tag                             : String [15];
   ShowSec                         : System. Word;
   ShowFlags                       : String [26];
 End;

 tFileArea = Record
   Name                            : String [72];
   ULPath, FileList                : String [80];
   DLPath                          : String [255];
   DL_Security, UL_Security,
   List_Security, MinSpeed,
   ShowSec                         : System. Word;
   DL_Flags, UL_Flags, List_Flags,
   ShowFlags                       : String [26];
   ScanNewFiles, CopyLocal         : Boolean;
   Group                           : String [100];
   FListFormat                     : tFListFormat;
 End;

 LimitRec = Record
   Level, SessionTime      : System. Word;
   KBLimit, Time, MinSpeed : LongInt;
   LoginTime               : TimeArray;
 End;

 tDoorWayCommands = (
   hcCls, hcCD, hcDir, hcTree, hcMkDir, hcRmDir, hcDirSize,
   hcDel, hcRename, hcCopy, hcArcView, hcType, hcLocate, hcShell,
   hcBoot, hcDate, hcTime, hcxDel, hcUL, hcDL, hcEdit,
   hcExit, hcTaskList, hcKill);

 DoorWayControlRec = Record
   Enter    : System. Word;
   flgEnter : String [26];
   SecLevel : Array [hcCls..hcKill] Of System. Word;
   SecFlags : Array [hcCls..hcKill] Of String [26];
   StartDir : String [80];
   Drives   : Array ['A'..'Z'] Of System. Word;
 End;

 tUpgradeMode = (umForever, umToday);

 UpgradeRec = Record
   Check, InformVia, Security : String [50];
   FileName                   : String [80];
   Mode                       : tUpgradeMode;
 End;

 CaseType = (NoCaps, Upper, Proper, Lower);
 TransferModeType = (Transmit, Receive);
 Str8 = String [8];

 PTagFileRec = ^TTagFileRec;
 TTagFileRec = Record
   GroupNum, AreaNum, Size : LongInt;
   PathName, FromName      : PString;
   Free                    : Boolean;
 End;

 PFileItem = ^TFileItem;
 TFileItem = Record
   FileName          : PString;
   Size              : LongInt;
   GroupNum, AreaNum : System. Word;
   Free              : Boolean;
 End;

 tEMSI = Record
   Session, CheckMail, CheckNewFiles, Allowed : Boolean;
   SoftWare                                   : String [50];
   Password                                   : String [15];
 End;

 tInAllow = Record
   RemIn, ConIn : Boolean;
 End;

 tMsg = Record
   FromUserName : String [36]; {Имя отправителя мессаджа}
   MessageText  : String [80]; {Тест сообщения}
   FromLineNum  : Byte;        {Номер линии отправителя}
 End;

 tListMode = (lmAll, lmExcludeCurrent, lmConference);
 tMsgType  = (mtUserMsg, mtConference);
 tRLCmode  = (trlcOpen4Stat, trlcOpen4All, trlcRead, trlcClose);

 tLine = Record
   Number    : Byte;                 {Номер линии}
   UserName  : String [36];          {Имя пользователя}
   Logged    : Boolean;              {Сидит ли}
   InConf    : Boolean;              {Участвует ли в конференции}
   LoginTime : String [8];           {Время входа на ббс}
 End;

 tProtocolConfig = Record
   Batch, Available           : Boolean;
   Selection                  : Char;
   WordOffs                   : Byte;
   Name, DLKeyWord, ULKeyWord : String [40];
   Log, List                  : String [80];
   DLCommand, ULCommand       : String;
 End;

{$I INC\finfo.inc}
